#apps/todos/serverless.yaml
service: todos


custom:
    serverless-offline:
        httpPort: 3003
        lambdaPort: 3005

functions:
  app: 
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          
provider:
  name: aws
  region: sa-east-1
  runtime: nodejs16.x
  stage: dev
  environment: 
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
    
  iam: 
    role: 
      statements: 
          - Effect: 'Allow'
            Action: 
              - 'dynamodb:DescribeTable'
              - 'dynamodb:Query'
              - 'dynamodb:Scan'
              - 'dynamodb:GetItem'
              - 'dynamodb:PutItem'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:DeleteItem'

            Resource: arn:aws:dynamodb:sa-east-1:*:table/TasksTable

resources: 
    Resources: 
      TasksTable: 
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: TasksTable
          AttributeDefinitions: 
              - AttributeName: id
                AttributeType: S

          KeySchema: 
              - AttributeName: id
                KeyType: HASH

          ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1  

      